### ISSUE TITLE
default view uid_mapping is not created 

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/slurm-pwalk#2]
if I want to join uid_mapping with file_metadata there is no uid_mapping view created as part of the bootstrapping script. I only have something like uid_mapping_201712231701 . We once had a uid_mapping but it was not recreated when storcrawl was rebuilt from scratch .

**Comment by dirkpetersen** [comment]
also we need to ensure that this error message does not show up for the ro user

psycopg2.ProgrammingError: permission denied for relation uid_mapping

**Comment by bmcgough** [comment]
I can create a view called 'uid_mapping' that points to the most recent tagged table.

The psycopg2 error is python, and none of the storcrawldb code is python. It is likely due to that view or table (uid_mapping) not being present and would be fixed by creating that view.

This is a lower priority than other issues.

**Comment by bmcgough** [comment]
Views for uid_mapping and gid_mapping are being created and permission being granted to the readonly user.
